from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, bb):
        bb.setObjectName("main_window")
        bb.resize(1163, 860)
        bc = QtGui.QIcon()
        bc.addPixmap(QtGui.QPixmap(":/icons/interface_images/icon_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bb.setWindowIcon(bc)
        bb.setAutoFillBackground(False)
        bb.setStyleSheet("")
        bb.setIconSize(QtCore.QSize(25, 25))
        self.a = QtWidgets.QWidget(bb)
        self.a.setStyleSheet("#Form {\n"
"    background: #2f353b;\n"
"}")
        self.a.setObjectName("Form")
        self.f = QtWidgets.QWidget(self.a)
        self.f.setGeometry(QtCore.QRect(0, 0, 1171, 861))
        self.f.setObjectName("horizontalLayoutWidget")
        self.bd = QtWidgets.QHBoxLayout(self.f)
        self.bd.setContentsMargins(0, 0, 0, 0)
        self.bd.setSpacing(0)
        self.bd.setObjectName("hlayout_main")
        self.be = QtWidgets.QVBoxLayout()
        self.be.setContentsMargins(3, 2, 0, 2)
        self.be.setSpacing(0)
        self.be.setObjectName("vlayout_left")
        self.bf = QtWidgets.QWidget(self.f)
        self.bf.setStyleSheet("background: #2f353b;")
        self.bf.setObjectName("widget_left_background")
        self.c_5 = QtWidgets.QWidget(self.bf)
        self.c_5.setGeometry(QtCore.QRect(10, 10, 2016, 851))
        self.c_5.setObjectName("verticalLayoutWidget_5")
        self.bg = QtWidgets.QVBoxLayout(self.c_5)
        self.bg.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bg.setContentsMargins(0, 2, 0, 2)
        self.bg.setSpacing(5)
        self.bg.setObjectName("vlayout_left_form")
        self.bh = QtWidgets.QHBoxLayout()
        self.bh.setObjectName("vspaser_left_form_top_layout")
        n = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bh.addItem(n)
        self.bg.addLayout(self.bh)
        self.bi = QtWidgets.QWidget(self.c_5)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.bi.sizePolicy().hasHeightForWidth())
        self.bi.setSizePolicy(b)
        self.bi.setMinimumSize(QtCore.QSize(340, 380))
        self.bi.setStyleSheet("#widget_create_form_background {\n"
"    border-style: outset;\n"
"    border-radius: 35px;\n"
"}\n"
"\n"
"* {\n"
"    background: #1d1e33;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #fffafa;\n"
"    background: #413d51;\n"
"    border-style: outset;\n"
"    border-radius: 6px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"QLineEdit:focus {\n"
"    color: #fffafa;\n"
"    background: #59506d;\n"
"}")
        self.bi.setObjectName("widget_create_form_background")
        self.c_3 = QtWidgets.QWidget(self.bi)
        self.c_3.setGeometry(QtCore.QRect(20, 40, 291, 291))
        self.c_3.setObjectName("verticalLayoutWidget_3")
        self.bj = QtWidgets.QVBoxLayout(self.c_3)
        self.bj.setContentsMargins(0, 0, 0, 0)
        self.bj.setSpacing(4)
        self.bj.setObjectName("vlayout_create_account_form")
        self.bk = QtWidgets.QLabel(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(14)
        self.bk.setFont(q)
        self.bk.setStyleSheet("color: #fffafa;\n"
"margin-bottom: 1em;")
        self.bk.setAlignment(QtCore.Qt.AlignCenter)
        self.bk.setObjectName("label_create_account")
        self.bj.addWidget(self.bk)
        self.bl = QtWidgets.QGridLayout()
        self.bl.setContentsMargins(2, 0, 2, 3)
        self.bl.setHorizontalSpacing(4)
        self.bl.setVerticalSpacing(1)
        self.bl.setObjectName("gridLayout_create_account_input")
        self.bm = QtWidgets.QLabel(self.c_3)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.bm.sizePolicy().hasHeightForWidth())
        self.bm.setSizePolicy(b)
        self.bm.setMinimumSize(QtCore.QSize(39, 39))
        self.bm.setMaximumSize(QtCore.QSize(42, 42))
        self.bm.setStyleSheet("margin-right: 2px;")
        self.bm.setText("")
        self.bm.setPixmap(QtGui.QPixmap(":/icons/interface_images/icon_user.png"))
        self.bm.setObjectName("label_create_user_icon")
        self.bl.addWidget(self.bm, 0, 1, 1, 1)
        self.bn = QtWidgets.QLabel(self.c_3)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.bn.sizePolicy().hasHeightForWidth())
        self.bn.setSizePolicy(b)
        self.bn.setMinimumSize(QtCore.QSize(39, 39))
        self.bn.setMaximumSize(QtCore.QSize(42, 42))
        self.bn.setStyleSheet("margin-right: 2px;")
        self.bn.setText("")
        self.bn.setPixmap(QtGui.QPixmap(":/icons/interface_images/icon_key.png"))
        self.bn.setObjectName("label_create_key_icon")
        self.bl.addWidget(self.bn, 1, 1, 1, 1)
        self.bo = QtWidgets.QLabel(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bo.setFont(q)
        self.bo.setStyleSheet("color: #fffafa;")
        self.bo.setWordWrap(False)
        self.bo.setObjectName("label_create_password")
        self.bl.addWidget(self.bo, 1, 0, 1, 1)
        self.bp = QtWidgets.QLabel(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bp.setFont(q)
        self.bp.setStyleSheet("color: #fffafa;")
        self.bp.setWordWrap(False)
        self.bp.setObjectName("label_create_login")
        self.bl.addWidget(self.bp, 0, 0, 1, 1)
        self.bq = QtWidgets.QLineEdit(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bq.setFont(q)
        self.bq.setToolTipDuration(-1)
        self.bq.setStyleSheet("")
        self.bq.setText("")
        self.bq.setEchoMode(QtWidgets.QLineEdit.Password)
        self.bq.setPlaceholderText("")
        self.bq.setClearButtonEnabled(True)
        self.bq.setObjectName("lineEdit_password_create_input")
        self.bl.addWidget(self.bq, 1, 2, 1, 1)
        self.br = QtWidgets.QLineEdit(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.br.setFont(q)
        self.br.setStyleSheet("")
        self.br.setText("")
        self.br.setPlaceholderText("")
        self.br.setClearButtonEnabled(True)
        self.br.setObjectName("lineEdit_login_create_input")
        self.bl.addWidget(self.br, 0, 2, 1, 1)
        self.bs = QtWidgets.QLineEdit(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bs.setFont(q)
        self.bs.setStyleSheet("")
        self.bs.setText("")
        self.bs.setEchoMode(QtWidgets.QLineEdit.Password)
        self.bs.setPlaceholderText("")
        self.bs.setClearButtonEnabled(True)
        self.bs.setObjectName("lineEdit_password_repeat_input")
        self.bl.addWidget(self.bs, 3, 2, 1, 1)
        self.bt = QtWidgets.QLabel(self.c_3)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.bt.sizePolicy().hasHeightForWidth())
        self.bt.setSizePolicy(b)
        self.bt.setMinimumSize(QtCore.QSize(39, 39))
        self.bt.setMaximumSize(QtCore.QSize(42, 42))
        self.bt.setStyleSheet("margin-right: 2px;")
        self.bt.setText("")
        self.bt.setPixmap(QtGui.QPixmap(":/icons/interface_images/icon_key.png"))
        self.bt.setObjectName("label_create_repeat_key_icon")
        self.bl.addWidget(self.bt, 3, 1, 1, 1)
        self.bu = QtWidgets.QLabel(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bu.setFont(q)
        self.bu.setStyleSheet("color: #fffafa;")
        self.bu.setWordWrap(False)
        self.bu.setObjectName("label_create_repeat_password")
        self.bl.addWidget(self.bu, 3, 0, 1, 1)
        self.bl.setColumnMinimumWidth(1, 42)
        self.bj.addLayout(self.bl)
        self.bv = QtWidgets.QPushButton(self.c_3)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.bv.sizePolicy().hasHeightForWidth())
        self.bv.setSizePolicy(b)
        self.bv.setMinimumSize(QtCore.QSize(120, 30))
        self.bv.setMaximumSize(QtCore.QSize(150, 40))
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(14)
        self.bv.setFont(q)
        self.bv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bv.setStyleSheet("#button_create_account {\n"
"    border-color: #08e8de;\n"
"    border-style: outset;\n"
"    border-radius: 5px;\n"
"\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-top: 2px;\n"
"    padding-bottom:  2px;\n"
"    margin-bottom: 8px;\n"
"\n"
"    background-color: #08e8de;\n"
"}\n"
"\n"
"#button_create_account::hover {\n"
"    background-color: #30d5c8;\n"
"}\n"
"\n"
"#button_create_account:pressed {\n"
"    background-color: #20b2aa;\n"
"}")
        self.bv.setAutoExclusive(False)
        self.bv.setAutoDefault(False)
        self.bv.setDefault(False)
        self.bv.setFlat(False)
        self.bv.setObjectName("button_create_account")
        self.bj.addWidget(self.bv)
        self.bw = QtWidgets.QLabel(self.c_3)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.bw.setFont(q)
        self.bw.setStyleSheet("color: #fffafa;")
        self.bw.setAlignment(QtCore.Qt.AlignCenter)
        self.bw.setOpenExternalLinks(False)
        self.bw.setObjectName("label_sign_in")
        self.bj.addWidget(self.bw)
        self.bg.addWidget(self.bi)
        self.bx = QtWidgets.QHBoxLayout()
        self.bx.setObjectName("vspaser_left_form_bottom_layout")
        n_1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.bx.addItem(n_1)
        self.bg.addLayout(self.bx)
        self.be.addWidget(self.bf)
        self.bd.addLayout(self.be)
        self.by = QtWidgets.QVBoxLayout()
        self.by.setContentsMargins(0, 2, 0, 2)
        self.by.setSpacing(0)
        self.by.setObjectName("vlayout_midle")
        self.widget_midle_background = QtWidgets.QWidget(self.f)
        self.widget_midle_background.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #2f353b, stop:1 #2f353b);")
        self.widget_midle_background.setObjectName("widget_midle_background")
        self.c = QtWidgets.QWidget(self.widget_midle_background)
        self.c.setGeometry(QtCore.QRect(10, 10, 371, 841))
        self.c.setObjectName("verticalLayoutWidget")
        self.bz = QtWidgets.QVBoxLayout(self.c)
        self.bz.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bz.setContentsMargins(3, 2, 3, 2)
        self.bz.setSpacing(5)
        self.bz.setObjectName("vlayout_offline")
        self.ca = QtWidgets.QHBoxLayout()
        self.ca.setObjectName("vspacer_offline_top_layout")
        n_2 = QtWidgets.QSpacerItem(20, 165, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ca.addItem(n_2)
        self.bz.addLayout(self.ca)
        self.cb = QtWidgets.QLabel(self.c)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(18)
        self.cb.setFont(q)
        self.cb.setStyleSheet("color: #fffafa;\n"
"margin-bottom: 1em;")
        self.cb.setAlignment(QtCore.Qt.AlignCenter)
        self.cb.setObjectName("label_ofline")
        self.bz.addWidget(self.cb)
        self.cc = QtWidgets.QLabel(self.c)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(11)
        self.cc.setFont(q)
        self.cc.setStyleSheet("color: #cdc5c2;\n"
"margin-bottom: 1em;")
        self.cc.setAlignment(QtCore.Qt.AlignCenter)
        self.cc.setObjectName("label_info")
        self.bz.addWidget(self.cc)
        self.cd = QtWidgets.QPushButton(self.c)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.cd.sizePolicy().hasHeightForWidth())
        self.cd.setSizePolicy(b)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(14)
        self.cd.setFont(q)
        self.cd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cd.setStyleSheet("#button_continue_offline {\n"
"    border-color: #08e8de;\n"
"    border-style: outset;\n"
"    border-radius: 5px;\n"
"    \n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-top: 2px;\n"
"    padding-bottom:  2px;\n"
"    margin-bottom: 8px;\n"
"    background-color: #08e8de;\n"
"}\n"
"\n"
"#button_continue_offline::hover {\n"
"    background-color: #30d5c8;\n"
"}\n"
"\n"
"#button_continue_offline:pressed {\n"
"    background-color: #20b2aa;\n"
"}")
        self.cd.setAutoDefault(False)
        self.cd.setDefault(False)
        self.cd.setFlat(False)
        self.cd.setObjectName("button_continue_offline")
        self.bz.addWidget(self.cd)
        self.ce = QtWidgets.QVBoxLayout()
        self.ce.setObjectName("vspacer_offline_botton_layout")
        n_3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ce.addItem(n_3)
        self.bz.addLayout(self.ce)
        self.by.addWidget(self.widget_midle_background)
        self.bd.addLayout(self.by)
        self.bx = QtWidgets.QVBoxLayout()
        self.bx.setContentsMargins(0, 2, 3, 2)
        self.bx.setSpacing(0)
        self.bx.setObjectName("vlayout_right")
        self.cf = QtWidgets.QWidget(self.f)
        self.cf.setStyleSheet("background: #2f353b;")
        self.cf.setObjectName("widget_right_background")
        self.c_4 = QtWidgets.QWidget(self.cf)
        self.c_4.setGeometry(QtCore.QRect(10, 10, 2016, 851))
        self.c_4.setObjectName("verticalLayoutWidget_4")
        self.cg = QtWidgets.QVBoxLayout(self.c_4)
        self.cg.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.cg.setContentsMargins(0, 2, 0, 2)
        self.cg.setSpacing(5)
        self.cg.setObjectName("vlayout_right_form")
        self.ch = QtWidgets.QHBoxLayout()
        self.ch.setObjectName("vspaser_form_top_layout")
        n_4 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ch.addItem(n_4)
        self.cg.addLayout(self.ch)
        self.ci = QtWidgets.QWidget(self.c_4)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.ci.sizePolicy().hasHeightForWidth())
        self.ci.setSizePolicy(b)
        self.ci.setMinimumSize(QtCore.QSize(340, 380))
        self.ci.setStyleSheet("#widget_login_form_background {\n"
"    border-style: outset;\n"
"    border-radius: 35px;\n"
"}\n"
"\n"
"* {\n"
"    background: #1d1e33;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #fffafa;\n"
"    background: #413d51;\n"
"    border-style: outset;\n"
"    border-radius: 6px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"QLineEdit:focus {\n"
"    background: #59506d;\n"
"}")
        self.ci.setObjectName("widget_login_form_background")
        self.c_2 = QtWidgets.QWidget(self.ci)
        self.c_2.setGeometry(QtCore.QRect(30, 40, 281, 311))
        self.c_2.setObjectName("verticalLayoutWidget_2")
        self.cj = QtWidgets.QVBoxLayout(self.c_2)
        self.cj.setContentsMargins(0, 0, 0, 0)
        self.cj.setSpacing(4)
        self.cj.setObjectName("vlayout_login_form")
        self.ck = QtWidgets.QLabel(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(14)
        self.ck.setFont(q)
        self.ck.setStyleSheet("color: #fffafa;\n"
"margin-bottom: 1em;")
        self.ck.setAlignment(QtCore.Qt.AlignCenter)
        self.ck.setObjectName("label_enter_account")
        self.cj.addWidget(self.ck)
        self.cl = QtWidgets.QGridLayout()
        self.cl.setContentsMargins(2, 0, 2, 3)
        self.cl.setHorizontalSpacing(4)
        self.cl.setVerticalSpacing(1)
        self.cl.setObjectName("gridLayout_form_input")
        self.cm = QtWidgets.QLineEdit(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.cm.setFont(q)
        self.cm.setStyleSheet("")
        self.cm.setText("")
        self.cm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cm.setPlaceholderText("")
        self.cm.setClearButtonEnabled(True)
        self.cm.setObjectName("lineEdit_password_input")
        self.cl.addWidget(self.cm, 1, 2, 1, 1)
        self.cn = QtWidgets.QLabel(self.c_2)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.cn.sizePolicy().hasHeightForWidth())
        self.cn.setSizePolicy(b)
        self.cn.setMinimumSize(QtCore.QSize(39, 39))
        self.cn.setMaximumSize(QtCore.QSize(42, 42))
        self.cn.setStyleSheet("margin-right: 2px;")
        self.cn.setText("")
        self.cn.setPixmap(QtGui.QPixmap(":/icons/interface_images/icon_key.png"))
        self.cn.setObjectName("label_key_icon")
        self.cl.addWidget(self.cn, 1, 1, 1, 1)
        self.co = QtWidgets.QLabel(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.co.setFont(q)
        self.co.setStyleSheet("color: #fffafa;")
        self.co.setWordWrap(False)
        self.co.setObjectName("label_password")
        self.cl.addWidget(self.co, 1, 0, 1, 1)
        self.cp = QtWidgets.QLabel(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.cp.setFont(q)
        self.cp.setStyleSheet("color: #fffafa;")
        self.cp.setWordWrap(False)
        self.cp.setObjectName("label_login")
        self.cl.addWidget(self.cp, 0, 0, 1, 1)
        self.cq = QtWidgets.QLabel(self.c_2)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.cq.sizePolicy().hasHeightForWidth())
        self.cq.setSizePolicy(b)
        self.cq.setMinimumSize(QtCore.QSize(39, 39))
        self.cq.setMaximumSize(QtCore.QSize(42, 42))
        self.cq.setStyleSheet("margin-right: 2px;")
        self.cq.setText("")
        self.cq.setPixmap(QtGui.QPixmap(":/icons/interface_images/icon_user.png"))
        self.cq.setObjectName("label_user_icon")
        self.cl.addWidget(self.cq, 0, 1, 1, 1)
        self.lineEdit_login_input = QtWidgets.QLineEdit(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.lineEdit_login_input.setFont(q)
        self.lineEdit_login_input.setStyleSheet("")
        self.lineEdit_login_input.setText("")
        self.lineEdit_login_input.setFrame(True)
        self.lineEdit_login_input.setPlaceholderText("")
        self.lineEdit_login_input.setClearButtonEnabled(True)
        self.lineEdit_login_input.setObjectName("lineEdit_login_input")
        self.cl.addWidget(self.lineEdit_login_input, 0, 2, 1, 1)
        self.cj.addLayout(self.cl)
        self.cr = QtWidgets.QPushButton(self.c_2)
        self.cr.setEnabled(True)
        b = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        b.setHorizontalStretch(0)
        b.setVerticalStretch(0)
        b.setHeightForWidth(self.cr.sizePolicy().hasHeightForWidth())
        self.cr.setSizePolicy(b)
        self.cr.setMinimumSize(QtCore.QSize(120, 30))
        self.cr.setMaximumSize(QtCore.QSize(150, 40))
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(14)
        self.cr.setFont(q)
        self.cr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cr.setStyleSheet("#button_enter {\n"
"    border-color: #08e8de;\n"
"    border-style: outset;\n"
"    border-radius: 5px;\n"
"\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    padding-top: 2px;\n"
"    padding-bottom:  2px;\n"
"    margin-bottom: 8px;\n"
"\n"
"    background-color: #08e8de;\n"
"}\n"
"\n"
"#button_enter::hover {\n"
"    background-color: #30d5c8;\n"
"}\n"
"\n"
"#button_enter:pressed {\n"
"    background-color: #20b2aa;\n"
"}")
        self.cr.setAutoExclusive(False)
        self.cr.setAutoDefault(False)
        self.cr.setDefault(False)
        self.cr.setFlat(False)
        self.cr.setObjectName("button_enter")
        self.cj.addWidget(self.cr)
        self.cs = QtWidgets.QLabel(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(12)
        self.cs.setFont(q)
        self.cs.setStyleSheet("color: #fffafa;")
        self.cs.setAlignment(QtCore.Qt.AlignCenter)
        self.cs.setOpenExternalLinks(False)
        self.cs.setObjectName("label_sign_up")
        self.cj.addWidget(self.cs)
        self.ct = QtWidgets.QLabel(self.c_2)
        q = QtGui.QFont()
        q.setFamily("Nirmala UI")
        q.setPointSize(10)
        self.ct.setFont(q)
        self.ct.setStyleSheet("color: #cdc5c2;\n"
"margin-top: 1em;")
        self.ct.setTextFormat(QtCore.Qt.AutoText)
        self.ct.setAlignment(QtCore.Qt.AlignCenter)
        self.ct.setWordWrap(True)
        self.ct.setObjectName("label_accaunt_info")
        self.cj.addWidget(self.ct)
        self.cj.setStretch(1, 1)
        self.cj.setStretch(2, 1)
        self.cg.addWidget(self.ci)
        self.cu = QtWidgets.QHBoxLayout()
        self.cu.setObjectName("vspaser_form_bottom_layout")
        n_5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cu.addItem(n_5)
        self.cg.addLayout(self.cu)
        self.bx.addWidget(self.cf)
        self.bd.addLayout(self.bx)
        bb.setCentralWidget(self.a)

        self.retranslateUi(bb)
        QtCore.QMetaObject.connectSlotsByName(bb)
        bb.setTabOrder(self.lineEdit_login_input, self.cm)
        bb.setTabOrder(self.cm, self.cr)
        bb.setTabOrder(self.cr, self.br)
        bb.setTabOrder(self.br, self.bq)
        bb.setTabOrder(self.bq, self.bs)
        bb.setTabOrder(self.bs, self.bv)
        bb.setTabOrder(self.bv, self.cd)

    def retranslateUi(self, bb):
        r = QtCore.QCoreApplication.translate
        bb.setWindowTitle(r("main_window", "Terds"))
        self.bk.setText(r("main_window", "Создать аккаунт"))
        self.bo.setText(r("main_window", "Пароль"))
        self.bp.setText(r("main_window", "Логин"))
        self.bu.setText(r("main_window", "Подтверждение"))
        self.bv.setText(r("main_window", "Создать"))
        self.bw.setText(r("main_window", ''))
        self.cb.setText(r("main_window", "Работать офлайн"))
        self.cc.setText(r("main_window", ""))
        self.cd.setText(r("main_window", "Продолжить"))
        self.ck.setText(r("main_window", "Войти в аккаунт"))
        self.co.setText(r("main_window", "Пароль"))
        self.cp.setText(r("main_window", "Логин"))
        self.cr.setText(r("main_window", "Войти"))
        self.cs.setText(r("main_window", "Нет аккаунта - создай его"))
        self.ct.setText(r("main_window", ""))